name: CycascWarpPoint
version: '1.5.1-paper1.20.4'
main: net.cycasc.mc.cycascwarppoint.CycascWarpPoint
api-version: '1.20'
authors: [Dunkelklinge1]
description: Minecraft server plugin that allows players to save coordinates to later teleport to that location (so-called “warppoints”).
website: https://www.cycasc.net
commands:
  sethome:
    description: Saves a home location where you can teleport to.
    usage: "Usage: /sethome [optional name]"
  home:
    description: Teleports you to the specified home.
    usage: "Usage: /home [optional name]"
  delhome:
    description: Deletes the specified home.
    usage: "Usage: /delhome [optional name]"
  listhome:
    description: Lists all your homes in chat that match the specified pattern.
    usage: "Usage: /listhome [optional pattern]"
  setwarp:
    description: Saves a warppoint where you can teleport to.
    usage: "Usage: /setwarp <required name>"
  warp:
    description: Teleports you to the specified warppoint.
    usage: "Usage: /warp <required name>"
  delwarp:
    description: Deletes the specified warppoint.
    usage: "Usage: /delwarp <required name>"
  listwarp:
    description: Lists all warppoints in chat and optionally ones that match the specified pattern.
    usage: "Usage: /listwarp [optional pattern]"
  listwarpcreator:
    description: Lists all warppoints in chat that match the specified creator.
    usage: "Usage: /listwarpcreator <creator>"